---
title: "Excelerate Program Analysis: A Two-Year Comparative Study of Global Learner Engagement and Outcomes (2023-2024)"
author: "Brian Mubia"
format:
  html:
    code-fold: true
    fig-width: 8
    fig-height: 6
    theme: flatly
execute:
  echo: true
  warning: false
  message: false
editor: visual
toc: true
number-sections: false
---

The **Excelerate Program**—a cornerstone of Saint Louis University’s (SLU) EXP initiative—connects global learners with real-world internships, competitions, skill-building courses, and workshops to earn digital badges and micro-scholarships. Designed to remove access barriers, the platform provides fully virtual, non-credit experiential learning opportunities that prepare learners for future careers and further academic study. This report presents a **two-year comparative study (2023–2024)** of global learner engagement. I analyze signups, applications, success and rejection rates, and internship and competition patterns to uncover which countries and learner demographics secured opportunities, how selectivity evolved, and how program popularity shifted over time. The goal is to provide data-driven insights into equity, regional engagement, and the effectiveness of Excelerate’s experiential model.

### [**Program Growth Metrics: Analysis of Signups and Applications**]{.underline}

The Excelerate program has shown strong growth momentum in 2024. Building on a solid foundation of 5,794 learner signups in 2023, the program has already attracted 2,764 additional signups in 2024 — signaling a significant year-over-year increase in global engagement. In terms of applications, learners submitted 3,737 applications in 2023 and 4777 in 2024, further highlighting a parallel rise in both program interest and participation.

To better understand the evolving interest in specific opportunities, the chart below illustrates the year-over-year differences in application volumes between 2023 and 2024. This highlights which opportunities experienced increased demand and which saw a decline in learner interest.